- name: Install nginx
  hosts: all
  become: true
  tasks:
    - name: Add the user 'speedypleath' and add it to 'sudo'
      ansible.builtin.user:
        name: speedypleath
        group: sudo

    - name: Add SSH key to 'speedypleath'
      ansible.posix.authorized_key:
        user: speedypleath
        state: present
        key: "{{ lookup('file', pub_key) }}"

    - name: Wait for apt to unlock
      become: true
      ansible.builtin.shell: while sudo fuser /var/lib/dpkg/lock >/dev/null 2>&1; do sleep 5; done;
      register: output
      changed_when: output.rc != 0

    - name: Install DigitalOcean repo key
      ansible.builtin.apt_key:
        url: https://repos.sonar.digitalocean.com/sonar-agent.asc
        state: present

    - name: Install DigitalOcean apt repo
      ansible.builtin.apt_repository:
        repo: deb https://repos.sonar.digitalocean.com/apt main main
        state: present
        update_cache: true

    - name: Update all packages
      ansible.builtin.apt:
        upgrade: dist
        update_cache: true
        cache_valid_time: 3600

    - name: Install Nginx and DigitalOcean agent
      action: ansible.builtin.apt name={{ item }} state=present
      with_items:
        - nginx
        - do-agent
